stages:
- Test
Testbsf:
  stage: test
  trigger:
    branch: dev
  variables:
    BUILD_NF: bsf
    CSAR_DEPLOYMENT: "true"
    BSF_RELEASE_TAG: 23.4.1-ocngf-new16
    INCLUDE_INTERNAL_ATS_FEATURES: "false"
    REPORT: "false"
    ATS_RELEASE_TAG: 23.4.1-ocngf-new16
    CUSTOM_NOTIFICATION_MESSAGE: "@rakhi testing 3"
    NAMESPACE: "o-devops-bsf6"
    TLS_VERSION: "1.2"

