stages:
- Test
Testbsf:
  stage: test
  trigger:
    branch: dev
  variables:
    BUILD_NF: bsf
    CSAR_DEPLOYMENT: "true"
    BSF_RELEASE_TAG: 23.4.1-ocngf-4232
    INCLUDE_INTERNAL_ATS_FEATURES: "false"
    POLICY_MODE: pcf
    REPORT: "false"
    ATS_RELEASE_TAG: 25.9.0-ocngf-4242
    CUSTOM_NOTIFICATION_MESSAGE: "@rakhi testing 2"

